### ISSUE TITLE
testing refactors

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1183]
- [ ] categorize tests
- [ ] refactor t_model file structure #1182
- [ ] remove unnecessary / duplicate tests #985 
- [ ] test gpkit.interactive #643 & #572
- [ ] be more clever about the different kinds of accuracy requirements in t_models #870
- [x] add python3 #1285
- [x] add tests to increase coverage #971 #1336
