### ISSUE TITLE
test sweeps + Tight

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1184]
- [x] test sweeps + Tight https://github.com/convexengineering/gpkit/issues/911
- [x] it'd be great if the results were united but still scalar before process_results https://github.com/convexengineering/gpkit/issues/860
- [x] debug should skip processing results https://github.com/convexengineering/gpkit/issues/1173 (kinda fixed: see #1220)
