### ISSUE TITLE
documentation desires

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#1280]
- [ ] add Berk's thesis
  - [ ] document ConstraintSet (#1223)
  - [ ] rewrite gpkit101 (#972)
  - [ ] add links to our favorite papers (and all papers citing gpkit) (#689)
  - [ ] document string/varkey access (#668)
  - [ ] document solution arrays (#565)
  - [ ] update inheritance flowchart (#350)
  - [ ] make sure all code in docs is in a running example (#303)
  - [ ] add "Signomial Programming 101" (#207)

**Comment by 1ozturkbe** [comment]
@bqpd @nillst I am interested in learning more about and documenting the gpkit.interactive tools (esp. dashboard) using some examples I created. @nillst if you have any example code or repos I can reference that would be great.

**Comment by bqpd** [comment]
All we've got is in the repo, really! Most of the methods are fairly self-documenting or have defaults.

**Comment by 1ozturkbe** [comment]
There seriously are no demos for these functions? It would have been nice to have a MWE and not to have to read through the methods to get started. I will have to do this after we merge SimPleAC so we can have a half-decent example.
