### ISSUE TITLE
debug windows install

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpkit#970]
- [ ] follow exactly and only the steps given on the install docs to install cvxopt and mosek
    - [ ] does cvxopt need to be unzipped?? (#811)
    - [ ] anything extra need to be done with mingw?  (#774)
  - [ ] add the appropriate catch for 32bit mosek in, to let users know why their install of mosek won't work with gpkit?
  - [ ] test un/reinstall. does pip uninstall hang? (#882)
